# Generated by Django 5.0.1 on 2024-01-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_rename_image_products_images_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image_type',
            field=models.CharField(choices=[('category', 'Category'), ('subcategory', 'Subcategory'), ('product', 'Product'), ('None', 'NONE')], default='None', max_length=20),
        ),
    ]
