# Generated by Django 5.0.1 on 2024-01-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_productimages_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='products',
            name='avg_rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='highlights',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='reviews_count',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='unique_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
