# Generated by Django 5.0.1 on 2024-01-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_remove_productcategory_name_products_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image_file',
            field=models.FileField(null=True, upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
